<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

// Make sure to import the User model

class CountrySeeder extends Seeder
{
    public function run()
    {
        // Create some permissions
        $countries = [
            // Original list
            'Afghanistan',
            'Albania',
            'Algeria',
            'Andorra',
            'Angola',
            'Antigua and Barbuda',
            'Argentina',
            'Armenia',
            'Australia',
            'Austria',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Bangladesh',
            'Barbados',
            'Belarus',
            'Belgium',
            'Belize',
            'Benin',
            'Bhutan',
            'Bolivia',
            'Bosnia and Herzegovina',
            'Botswana',
            'Brazil',
            'Brunei',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Cabo Verde',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Central African Republic',
            'Chad',
            'Chile',
            'China',
            'Colombia',
            'Comoros',
            'Congo (Brazzaville)',
            'Congo (Kinshasa)',
            'Costa Rica',
            'Croatia',
            'Cuba',
            'Cyprus',
            'Czech Republic',
            'Denmark',
            'Djibouti',
            'Dominica',
            'Dominican Republic',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guinea',
            'Eritrea',
            'Estonia',
            'Eswatini',
            'Ethiopia',
            'Fiji',
            'Finland',
            'France',
            'Gabon',
            'Gambia',
            'Georgia',
            'Germany',
            'Ghana',
            'Greece',
            'Grenada',
            'Guatemala',
            'Guinea',
            'Guinea-Bissau',
            'Guyana',
            'Haiti',
            'Honduras',
            'Hungary',
            'Iceland',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Ireland',
            'Israel',
            'Italy',
            'Jamaica',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Korea, North',
            'Korea, South',
            'Kosovo',
            'Kuwait',
            'Kyrgyzstan',
            'Laos',
            'Latvia',
            'Lebanon',
            'Lesotho',
            'Liberia',
            'Libya',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives',
            'Mali',
            'Malta',
            'Marshall Islands',
            'Mauritania',
            'Mauritius',
            'Mexico',
            'Micronesia',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Morocco',
            'Mozambique',
            'Myanmar (Burma)',
            'Namibia',
            'Nauru',
            'Nepal',
            'Netherlands',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'North Macedonia',
            'Norway',
            'Oman',
            'Pakistan',
            'Palau',
            'Palestine',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Poland',
            'Portugal',
            'Qatar',
            'Romania',
            'Russia',
            'Rwanda',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Vincent and the Grenadines',
            'Samoa',
            'San Marino',
            'Sao Tome and Principe',
            'Saudi Arabia',
            'Senegal',
            'Serbia',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Slovakia',
            'Slovenia',
            'Solomon Islands',
            'Somalia',
            'South Africa',
            'South Sudan',
            'Spain',
            'Sri Lanka',
            'Sudan',
            'Suriname',
            'Sweden',
            'Switzerland',
            'Syria',
            'Taiwan',
            'Tajikistan',
            'Tanzania',
            'Thailand',
            'Timor-Leste',
            'Togo',
            'Tonga',
            'Trinidad and Tobago',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Tuvalu',
            'Uganda',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'United States',
            'Uruguay',
            'Uzbekistan',
            'Vanuatu',
            'Vatican City',
            'Venezuela',
            'Vietnam',
            'Yemen',
            'Zambia',
            'Zimbabwe',
            'Åland Islands',
            'Faroe Islands',
            'Greenland',
            'Hong Kong',
            'Macau',
            'Western Sahara',
            'Cook Islands',
            'Niue',
            'New Caledonia',
            'French Polynesia',

            'Aruba',
            'Bermuda',
            'British Virgin Islands',
            'Cayman Islands',
            'Falkland Islands',
            'Gibraltar',
            'Guernsey',
            'Isle of Man',
            'Jersey',
            'Montserrat',
            'Pitcairn Islands',
            'Saint Helena',
            'South Georgia and the South Sandwich Islands',
            'Turks and Caicos Islands',
            'Anguilla',
            'American Samoa',
            'Guam',
            'Northern Mariana Islands',
            'Puerto Rico',
            'U.S. Virgin Islands',
            'French Guiana',
            'Guadeloupe',
            'Martinique',
            'Mayotte',
            'Réunion',
            'Saint Barthélemy',
            'Saint Martin',
            'Saint Pierre and Miquelon',
            'Wallis and Futuna',
            'Tokelau',
            'Christmas Island',
            'Cocos (Keeling) Islands',
            'Norfolk Island',
            'Ashmore and Cartier Islands',
            'Coral Sea Islands',
            'Heard Island and McDonald Islands',
            'Australian Antarctic Territory',
            'Bouvet Island',
            'Svalbard and Jan Mayen',
            'Antarctica',
            'Curacao',
            'Sint Maarten',
            'Bonaire',
            'Saint Eustatius',
            'Saba',
            'Azores',
            'Madeira',
            'Canary Islands',
            'Ceuta',
            'Melilla',
            'Nagorno-Karabakh',
            'Abkhazia',
            'South Ossetia',
            'Transnistria',
            'Northern Cyprus',
            'Somaliland',
            'Basque Country',
            'Scotland',
            'Wales',
            'Northern Ireland',
            'England',
            'Wallonia',
            'Flanders',
            'Galápagos Islands',
            'Easter Island',
            'Chagos Archipelago',
            'Ross Dependency',
            'Macquarie Island',
            'Clipperton Island',
            'Caribbean Netherlands',
            'Aland Islands',
            'European Union',
            'Melanesia',
            'Micronesia (Region)',
            'Polynesia (Region)',
            'Caribbean',
            'Central America',
            'South America',
            'North America',
            'Southern Africa',
            'East Africa',
            'West Africa',
            'Central Africa',
            'Northern Africa',
            'Middle East',
            'Southeast Asia',
            'South Asia',
            'Central Asia',
            'East Asia',
            'Oceania',
        ];

        foreach ($countries as $data) {
            Country::create([
                'name' => $data,
            ]);
        }
    }
}
